repos:
  - repo: local
    hooks:
      - id: black
        name: format
        entry: poetry run black
        language: system
        types: [python]
        stages: [commit]
      - id: mypy
        name: type check
        entry: poetry run mypy
        language: system
        types: [python]
        stages: [commit]
